<#
.SYNOPSIS
    Creates Okta OIDC web applications in a target org (for example oktapreview) from an export
    made by Export-OktaWebApps.ps1.

.DESCRIPTION
    For every app in the export file this script:
      1. Replaces production URLs with test URLs, if you give it a URL map file (optional).
      2. Skips the app if an app with the same label already exists in the target org.
      3. Creates the app (a new Client ID and client secret are generated by Okta).
      4. Identity Engine only: assigns an authentication policy to the app.
      5. Optional: assigns the same groups (matched by group name) that the app had in the source org.

    Always run it with -DryRun first. A dry run signs in and checks everything but creates nothing.

    A results CSV is written to the output folder, listing each app and what happened to it.

.PARAMETER OrgUrl
    The Okta org to create the apps in, e.g. https://yourcompany.oktapreview.com

.PARAMETER ExportFile
    The .json file created by Export-OktaWebApps.ps1.

.PARAMETER SignInFlow
    IdentityEngine - Set the apps up for Okta Identity Engine: each app is given an authentication
                     policy (see -AuthenticationPolicyName). The target org must be an Identity Engine org.
    Classic        - Set the apps up the Classic way: no authentication policy is assigned, and the
                     Identity-Engine-only "interaction_code" grant type is removed. On an Identity Engine
                     org, Okta then applies its default authentication policy to the app.

.PARAMETER AuthenticationPolicyName
    Identity Engine only. The name of the authentication policy to assign to every created app,
    e.g. "Any two factors". If you leave this out, the script uses the policy with the same name
    the app had in the source org, and if that does not exist, Okta's default policy.

.PARAMETER EnableInteractionCode
    Identity Engine only. Adds the "Interaction Code" grant type to each app. Only use this if the
    app uses Okta's embedded sign-in (Identity Engine SDKs) and your org has Interaction Code enabled.

.PARAMETER UrlMapFile
    A CSV file with two columns, Find and Replace. Every URL in the app that contains a Find value has
    that part replaced. See url-map.sample.csv.

.PARAMETER AssignGroups
    Also assign each app to the groups it had in the source org. Groups are matched by exact name;
    groups that do not exist in the target org are reported and skipped.

.PARAMETER KeepClientId
    Create the apps with the same Client ID they have in the source org instead of a new random one.

.PARAMETER IssuerMode
    Overrides the issuer mode for every app. Use ORG_URL if the target org has no custom domain
    and apps fail to create with an issuer_mode error.

.PARAMETER CreateInactive
    Create the apps deactivated. By default an app is created active if it was active in the source.

.PARAMETER Label
    Only import apps whose label matches one of these patterns. * is a wildcard.

.PARAMETER DryRun
    Show what would happen without creating anything.

.PARAMETER SaveClientSecrets
    Write the new Client IDs and client secrets to a separate CSV file. Treat that file like a
    password: store it securely and delete it when you are done.

.PARAMETER AuthMethod
    ApiToken (default) or Browser. See migration-work.md.

.PARAMETER ClientId
    Only for -AuthMethod Browser: the Client ID of the "Okta PowerShell CLI" app in the target org.

.PARAMETER ApiTokenEnvVar
    Name of an environment variable holding the target org API token. Default: OKTA_TARGET_API_TOKEN.

.PARAMETER AllowSameOrg
    Allow importing into the same org the export came from. Off by default as a safety check.

.EXAMPLE
    ./Import-OktaWebApps.ps1 -OrgUrl https://yourcompany.oktapreview.com -ExportFile ./exports/okta-web-apps-yourcompany-2026-09-27_101500.json -SignInFlow IdentityEngine -DryRun

.EXAMPLE
    ./Import-OktaWebApps.ps1 -OrgUrl https://yourcompany.oktapreview.com -ExportFile ./exports/okta-web-apps-yourcompany-2026-09-27_101500.json -SignInFlow Classic -UrlMapFile ./url-map.csv -AssignGroups
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$OrgUrl,

    [Parameter(Mandatory)]
    [string]$ExportFile,

    [Parameter(Mandatory)]
    [ValidateSet('IdentityEngine', 'Classic')]
    [string]$SignInFlow,

    [string]$AuthenticationPolicyName,

    [switch]$EnableInteractionCode,

    [string]$UrlMapFile,

    [switch]$AssignGroups,

    [switch]$KeepClientId,

    [ValidateSet('ORG_URL', 'CUSTOM_URL', 'DYNAMIC')]
    [string]$IssuerMode,

    [switch]$CreateInactive,

    [string[]]$Label = @('*'),

    [switch]$DryRun,

    [switch]$SaveClientSecrets,

    [ValidateSet('ApiToken', 'Browser')]
    [string]$AuthMethod = 'ApiToken',

    [string]$ClientId,

    [string]$ApiTokenEnvVar = 'OKTA_TARGET_API_TOKEN',

    [string]$OutputFolder = (Join-Path $PSScriptRoot 'exports'),

    [switch]$AllowSameOrg
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'OktaMigration.Common.ps1')

# Replaces URL fragments (from the URL map) in every URL-looking string inside an object.
function Update-UrlsInObject {
    param($Object, $Map)

    if ($null -eq $Object -or $Map.Count -eq 0) { return }

    $apply = {
        param([string]$Text)
        if ($Text -notmatch '://') { return $Text }
        foreach ($row in $Map) {
            $Text = $Text.Replace($row.Find, $row.Replace, [System.StringComparison]::OrdinalIgnoreCase)
        }
        return $Text
    }

    if ($Object -is [System.Array]) {
        for ($i = 0; $i -lt $Object.Count; $i++) {
            if ($Object[$i] -is [string]) { $Object[$i] = & $apply $Object[$i] }
            else { Update-UrlsInObject $Object[$i] $Map }
        }
    }
    elseif ($Object -is [System.Management.Automation.PSCustomObject]) {
        foreach ($prop in $Object.PSObject.Properties) {
            if ($prop.Value -is [string]) { $prop.Value = & $apply $prop.Value }
            else { Update-UrlsInObject $prop.Value $Map }
        }
    }
}

# Sets or adds a property on an object.
function Set-Prop {
    param($Object, [string]$Name, $Value)
    if ($Object.PSObject.Properties[$Name]) { $Object.$Name = $Value }
    else { $Object | Add-Member -NotePropertyName $Name -NotePropertyValue $Value }
}

$results = [System.Collections.Generic.List[object]]::new()
$secrets = [System.Collections.Generic.List[object]]::new()

try {
    $OrgUrl = Get-NormalizedOrgUrl $OrgUrl

    Write-Step "Reading the export file"
    if (-not (Test-Path $ExportFile)) { throw "Export file not found: $ExportFile" }
    $export = Get-Content -Path $ExportFile -Raw | ConvertFrom-Json
    if (-not $export.PSObject.Properties['apps'] -or $export.exportFormatVersion -ne 1) {
        throw "'$ExportFile' is not an export file created by Export-OktaWebApps.ps1."
    }
    $apps = @($export.apps | Where-Object {
        $appLabel = $_.definition.label
        @($Label | Where-Object { $appLabel -like $_ }).Count -gt 0
    })
    Write-Ok "Export from $($export.sourceOrg) taken $($export.exportedAt): $(@($export.apps).Count) app(s), $($apps.Count) selected."
    if ($apps.Count -eq 0) { throw "No apps in the export match -Label $($Label -join ', ')." }

    if (-not $AllowSameOrg -and $export.sourceOrg -eq $OrgUrl) {
        throw "The target org ($OrgUrl) is the same org the export came from. Use -AllowSameOrg if you really mean this."
    }

    $urlMap = @()
    if ($UrlMapFile) {
        Write-Step "Reading the URL map"
        if (-not (Test-Path $UrlMapFile)) { throw "URL map file not found: $UrlMapFile" }
        $urlMap = @(Import-Csv -Path $UrlMapFile | Where-Object { $_.Find })
        if ($urlMap.Count -gt 0 -and -not ($urlMap[0].PSObject.Properties['Find'] -and $urlMap[0].PSObject.Properties['Replace'])) {
            throw "The URL map file must have the column headings Find and Replace."
        }
        foreach ($row in $urlMap) { Write-Ok "'$($row.Find)'  ->  '$($row.Replace)'" }
    }

    Write-Step "Loading the Okta PowerShell module"
    Import-OktaModuleForMigration

    Write-Step "Checking $OrgUrl"
    $engine = Get-OktaOrgEngine $OrgUrl
    Write-Ok "Org engine: $engine"
    if ($SignInFlow -eq 'IdentityEngine' -and $engine -eq 'Classic') {
        throw "You chose -SignInFlow IdentityEngine, but $OrgUrl is a Classic Engine org. Use -SignInFlow Classic."
    }
    if ($SignInFlow -eq 'Classic' -and $engine -eq 'IdentityEngine') {
        Write-Warn "$OrgUrl is an Identity Engine org. With -SignInFlow Classic no policy is assigned, so Okta applies its default authentication policy."
    }
    if ($SignInFlow -eq 'Classic' -and ($AuthenticationPolicyName -or $EnableInteractionCode)) {
        throw "-AuthenticationPolicyName and -EnableInteractionCode only work with -SignInFlow IdentityEngine."
    }

    Write-Step "Signing in to $OrgUrl"
    Connect-OktaOrg -OrgUrl $OrgUrl -AuthMethod $AuthMethod -ApiTokenEnvVar $ApiTokenEnvVar -ClientId $ClientId `
        -Scopes @('okta.apps.manage', 'okta.apps.read', 'okta.groups.read', 'okta.policies.read')

    # Authentication policies in the target org, by name.
    $policiesByName = @{}
    $forcedPolicy = $null
    if ($SignInFlow -eq 'IdentityEngine') {
        Write-Step "Reading authentication policies"
        $policies = Get-OktaAllPages {
            param($next)
            if ($next) { Invoke-OktaListPolicies -Type 'ACCESS_POLICY' -Uri $next -WithHttpInfo }
            else { Invoke-OktaListPolicies -Type 'ACCESS_POLICY' -WithHttpInfo }
        }
        foreach ($p in $policies) { $policiesByName[$p.name] = $p }
        Write-Ok "Found $($policies.Count) authentication policies: $(@($policies | ForEach-Object { $_.name }) -join ', ')"
        if ($AuthenticationPolicyName) {
            if (-not $policiesByName.ContainsKey($AuthenticationPolicyName)) {
                throw "No authentication policy named '$AuthenticationPolicyName' exists in $OrgUrl."
            }
            $forcedPolicy = $policiesByName[$AuthenticationPolicyName]
        }
    }

    Write-Step "Reading apps that already exist in $OrgUrl"
    $existing = Get-OktaAllPages {
        param($next)
        if ($next) { Invoke-OktaListApplications -Uri $next -WithHttpInfo }
        else { Invoke-OktaListApplications -Limit 200 -WithHttpInfo }
    }
    $existingLabels = @{}
    foreach ($e in $existing) { $existingLabels[$e.label.ToLowerInvariant()] = $e.id }
    Write-Ok "$($existing.Count) app(s) already exist."

    $groupCache = @{}
    function Find-TargetGroup([string]$Name) {
        if ($groupCache.ContainsKey($Name)) { return $groupCache[$Name] }
        $found = @(Invoke-OktaListGroups -Q $Name -Limit 200) | Where-Object { $_.profile.name -eq $Name } | Select-Object -First 1
        $groupCache[$Name] = $found
        return $found
    }

    if ($DryRun) {
        Write-Host ""
        Write-Host "DRY RUN: nothing will be created." -ForegroundColor Magenta
    }

    Write-Step "Creating apps"
    foreach ($entry in $apps) {
        $def = Copy-DeepObject $entry.definition
        $source = $entry.source
        $appLabel = $def.label
        $row = [ordered]@{
            Label = $appLabel; Result = ''; NewAppId = ''; NewClientId = ''
            AuthenticationPolicy = ''; GroupsAssigned = ''; GroupsMissing = ''
            SignInRedirectUris = ''; SignOutRedirectUris = ''; Message = ''
        }

        try {
            Update-UrlsInObject $def $urlMap

            $oauthCreds = $def.credentials.oauthClient
            if (-not $KeepClientId -and $oauthCreds.PSObject.Properties['client_id']) {
                $oauthCreds.PSObject.Properties.Remove('client_id')
            }

            $oauth = $def.settings.oauthClient
            $grants = [System.Collections.Generic.List[string]]::new()
            foreach ($g in @(Get-Prop $oauth 'grant_types')) { if ($g) { $grants.Add($g) } }
            if ($SignInFlow -eq 'Classic') { [void]$grants.Remove('interaction_code') }
            if ($EnableInteractionCode -and -not $grants.Contains('interaction_code')) { $grants.Add('interaction_code') }
            Set-Prop $oauth 'grant_types' ([string[]]$grants)
            if ($IssuerMode) { Set-Prop $oauth 'issuer_mode' $IssuerMode }

            $row.SignInRedirectUris = @(Get-Prop $oauth 'redirect_uris') -join ' | '
            $row.SignOutRedirectUris = @(Get-Prop $oauth 'post_logout_redirect_uris') -join ' | '

            # Which authentication policy to use.
            $policy = $null
            if ($SignInFlow -eq 'IdentityEngine') {
                if ($forcedPolicy) { $policy = $forcedPolicy }
                elseif ($source.authenticationPolicyName -and $policiesByName.ContainsKey($source.authenticationPolicyName)) {
                    $policy = $policiesByName[$source.authenticationPolicyName]
                }
            }
            $row.AuthenticationPolicy = if ($policy) { $policy.name } elseif ($SignInFlow -eq 'IdentityEngine') { '(Okta default)' } else { '(Classic - none assigned)' }

            if ($existingLabels.ContainsKey($appLabel.ToLowerInvariant())) {
                $row.Result = 'Skipped'
                $row.Message = "An app labelled '$appLabel' already exists (id $($existingLabels[$appLabel.ToLowerInvariant()]))."
                Write-Warn "$appLabel : already exists, skipped."
                continue
            }

            $sourceGroups = @($source.groups | Where-Object { $_ -and $_.name })

            if ($DryRun) {
                $row.Result = 'DryRun'
                if ($AssignGroups) {
                    $missing = @($sourceGroups | Where-Object { -not (Find-TargetGroup $_.name) } | ForEach-Object { $_.name })
                    $row.GroupsAssigned = @($sourceGroups | Where-Object { $missing -notcontains $_.name } | ForEach-Object { $_.name }) -join ', '
                    $row.GroupsMissing = $missing -join ', '
                }
                Write-Ok "$appLabel : would be created. Policy: $($row.AuthenticationPolicy). Grant types: $($grants -join ', ')"
                Write-Host "           Sign-in redirect URIs : $($row.SignInRedirectUris)" -ForegroundColor DarkGray
                Write-Host "           Sign-out redirect URIs: $($row.SignOutRedirectUris)" -ForegroundColor DarkGray
                if ($row.GroupsMissing) { Write-Warn "$appLabel : these groups do not exist in the target org: $($row.GroupsMissing)" }
                continue
            }

            $activate = (-not $CreateInactive) -and ($source.status -eq 'ACTIVE')
            $created = New-OktaApplication -Application $def -Activate $activate
            $row.NewAppId = $created.id
            $row.NewClientId = $created.credentials.oauthClient.client_id
            $existingLabels[$appLabel.ToLowerInvariant()] = $created.id
            $row.Result = 'Created'
            Write-Ok "$appLabel : created (app id $($created.id), client id $($row.NewClientId))."

            $secret = Get-Prop $created.credentials.oauthClient 'client_secret'
            if ($SaveClientSecrets) {
                $secrets.Add([pscustomobject]@{ Label = $appLabel; ClientId = $row.NewClientId; ClientSecret = $secret })
            }

            $warnings = @()
            if ($policy) {
                try {
                    Set-OktaApplicationPolicy -AppId $created.id -PolicyId $policy.id | Out-Null
                    Write-Ok "$appLabel : authentication policy '$($policy.name)' assigned."
                }
                catch {
                    $warnings += "Could not assign policy '$($policy.name)': $(Get-OktaErrorText $_)"
                }
            }

            if ($AssignGroups -and $sourceGroups.Count -gt 0) {
                $assigned = @(); $missing = @()
                foreach ($g in $sourceGroups) {
                    $target = Find-TargetGroup $g.name
                    if (-not $target) { $missing += $g.name; continue }
                    try {
                        $body = if ($null -ne $g.priority) { [pscustomobject]@{ priority = $g.priority } } else { [pscustomobject]@{} }
                        New-OktaApplicationGroupAssignment -AppId $created.id -GroupId $target.id -ApplicationGroupAssignment $body | Out-Null
                        $assigned += $g.name
                    }
                    catch {
                        $warnings += "Could not assign group '$($g.name)': $(Get-OktaErrorText $_)"
                    }
                }
                $row.GroupsAssigned = $assigned -join ', '
                $row.GroupsMissing = $missing -join ', '
                if ($assigned) { Write-Ok "$appLabel : assigned groups: $($assigned -join ', ')" }
                if ($missing) { $warnings += "Groups not found in target org: $($missing -join ', ')" }
            }

            if ($warnings) {
                $row.Result = 'CreatedWithWarnings'
                $row.Message = $warnings -join ' | '
                foreach ($w in $warnings) { Write-Warn "$appLabel : $w" }
            }
        }
        catch {
            $row.Result = 'Failed'
            $row.Message = Get-OktaErrorText $_
            Write-Fail "$appLabel : $($row.Message)"
        }
        finally {
            $results.Add([pscustomobject]$row)
        }
    }
}
catch {
    Write-Host ""
    Write-Fail "Import stopped: $(Get-OktaErrorText $_)"
    $stopped = $true
}

if ($results.Count -gt 0) {
    Write-Step "Writing results"
    if (-not (Test-Path $OutputFolder)) { New-Item -ItemType Directory -Path $OutputFolder | Out-Null }
    $orgName = ([System.Uri]$OrgUrl).Host.Split('.')[0]
    $stamp = Get-Date -Format 'yyyy-MM-dd_HHmmss'
    $kind = if ($DryRun) { 'dryrun' } else { 'import' }
    $resultPath = Join-Path $OutputFolder "$kind-results-$orgName-$stamp.csv"
    $results | Export-Csv -Path $resultPath -NoTypeInformation -Encoding utf8
    Write-Ok "Results: $resultPath"

    if ($secrets.Count -gt 0) {
        $secretPath = Join-Path $OutputFolder "client-secrets-$orgName-$stamp.csv"
        $secrets | Export-Csv -Path $secretPath -NoTypeInformation -Encoding utf8
        Write-Warn "Client secrets written to $secretPath. Store them somewhere safe, then delete this file."
    }

    Write-Host ""
    $results | Group-Object Result | ForEach-Object { Write-Host ("{0,-22} {1}" -f $_.Name, $_.Count) }
}

if ($stopped -or @($results | Where-Object { $_.Result -eq 'Failed' }).Count -gt 0) { exit 1 }
